### ISSUE TITLE
development status now parsed from `setup.json`

### ISSUE THREAD

**Issue by ltalirz** [environ-developers/aiida-environ#1]
In order to remove duplication, we're removing the development status from the aiida plugin registry   and parsing it from the `setup.json` instead.

Just mentioning that on the code registry, the plugin was listed as "beta", while the `setup.json` currently indicates "alpha".
https://github.com/environ-developers/aiida-environ/blob/6bfecf7159d3613c4fbfb277deb8f1f1b7d4ad1a/setup.json#L7

Feel free to close this issue if you're fine with the "alpha" status - otherwise please update the `setup.json` of the relevant branch.

**Comment by matthew-truscott** [comment]
Thanks for this. We'll be working on a release soon, so I'll update `setup.json` at that time.
